# This file will allow you to install all the packages we use in the entire course in one go. 
# Presuming the installation goes correctly you should be able to run all markdown files. 


# Advise: Press "no" on the option of restarting R before the installation unless you have a good reason for not restarting R.
# By pressing this allows all packages to be installed directly, without having to restart R between every installation.
install.packages(c("jtools",
"forcats",
"tidyverse",
"plotly",
"dplyr",
"plyr",
"broom.mixed",
"parallel",
"doSNOW",
"ISLR",
"jtools",
"grid",
"gridExtra",
"here",
"rattle",
"MLeval",
"klaR",
"mice",
"ggplot2",
"ggcorrplot",
"ggstance",
"RColorBrewer",
"purrr",
"naniar",
"rpart.plot",
"visNetwork",
"Polychrome",
"papeR",
"xtable",
"kableExtra",
"modelsummary",
"knitr",
"rpart",
"caret",
"glmnet",
"regclass",
"MLmetrics",
"pROC",
"MASS",
"ROSE",
"e1071",
"leaps",
"AppliedPredictiveModeling",
"randomForest",
"factoextra",
"cluster",
"eclust",
"smotefamily",
"tidymodels",
"themis",
"recipes"))
